/**
 * api/generate-guide.js
 * ------------------------------------------------------------------
 * Vercel serverless function. This is the ONLY place the Anthropic API
 * key is used: it lives in process.env.ANTHROPIC_API_KEY, set in the
 * Vercel dashboard, and is never sent to or readable by the browser.
 *
 * Two design decisions this file exists to enforce:
 *
 * 1. CONSTRAINED REASONING, NOT RECALL.
 *    Claude is not asked "what does GDPR say about X" and trusted to
 *    remember correctly. Every fixed legal fact (the six interventions
 *    and their citations, the Article 22 caveat, the customer notice,
 *    the disclaimer) lives in data/reference.js, a file a human has
 *    checked against primary sources, and is assembled directly by
 *    assembleGuide() below rather than asked of the model at all. The
 *    model's only job is the genuinely sector-specific part that can't
 *    be pre-written: the stakes heading, the stakes explanation, and
 *    2-3 sector risk examples, consistent with the fixed content it's
 *    given but never asked to reproduce that content itself. This is
 *    what makes the output's legal content independently checkable: it
 *    was checked before the model ever saw the request, and the model
 *    never gets a chance to alter it in transit.
 *
 * 2. A VERIFIED FALLBACK, ALWAYS.
 *    If the live call fails for any reason (network error, API outage,
 *    malformed response, timeout, or simply a missing API key), this
 *    function does not return an error. It runs the same assembleGuide()
 *    step over pre-written, pre-verified content from
 *    data/fallback-guides.js instead, flagged isFallback: true, so a
 *    live demo or an examiner's session never breaks because of
 *    infrastructure outside this project's control.
 * ------------------------------------------------------------------
 */

const Anthropic = require("@anthropic-ai/sdk");
const {
  SECTORS,
  ARTICLE_22_CAVEAT,
  CUSTOMER_NOTICE,
  DISCLAIMER,
  buildInterventions,
  getSector,
} = require("../data/reference");
const { getFallbackContent } = require("../data/fallback-guides");

// Model is configurable via env var rather than hardcoded, so the model
// can be swapped (e.g. for a cheaper tier) without a code change, but
// ships with a sensible default so the app works out of the box.
const MODEL = process.env.ANTHROPIC_MODEL || "claude-opus-5";

// The strict JSON schema the model's response is validated against.
// This is deliberately small: stakesHeading, stakesExplanation, and
// sectorRisks are the only content that genuinely needs live,
// sector-specific writing. Everything else in a guide is fixed and
// assembled in code (see assembleGuide below), so there is nothing
// else for the model to be asked for.
const OUTPUT_SCHEMA = {
  type: "object",
  properties: {
    stakesHeading: { type: "string" },
    stakesExplanation: { type: "string" },
    sectorRisks: {
      type: "array",
      items: { type: "string" },
    },
  },
  required: ["stakesHeading", "stakesExplanation", "sectorRisks"],
  additionalProperties: false,
};

/**
 * Renders the fixed reference block into the system prompt text. The
 * six interventions, the Article 22 caveat, and the customer notice are
 * not included here at all: the model is never asked to reproduce them,
 * so there is nothing about them to instruct it on.
 */
function buildSystemPrompt(sector) {
  const stakesGrounding = sector.stakesGrounding
    ? `Legal grounding for this sector's stakes tier: ${sector.stakesGrounding}`
    : "This is a standard-stakes sector. No elevated legal grounding beyond the six fixed governance interventions applies specifically to it.";

  return `You are the content-generation engine inside SixPoint, an AI governance guide generator for SMEs. You are producing the sector-specific portion of ONE guide for ONE sector, for a non-technical, non-legal small business owner. English only.

CRITICAL CONSTRAINT, READ CAREFULLY:
You are not being asked to recall or interpret GDPR or the EU AI Act from your own training, and you are not being asked to write the guide's six governance interventions, its GDPR Article 22 note, its customer-notice advice, or its disclaimer: those are fixed and are added by this application after you respond, not generated by you. Your only job is to write three fields, grounded in the sector context below, that are consistent with (never contradicting) a set of six fixed governance interventions covering vendor accountability, a data processing record, default settings, human review of AI output, pattern/fairness checks, and incident response. Do not invent additional legal obligations or citations, and do not describe or restate the six interventions yourself, they are not part of your output.

TARGET SECTOR: ${sector.label}
STAKES TIER: ${sector.stakesTier} (${stakesGrounding})

OUTPUT FIELDS:
- stakesHeading: a short heading naming the stakes tier and why, specific to ${sector.label}
- stakesExplanation: 1-2 sentences giving the sector's own stakes rationale (do not mention Article 22 or automated decision-making generally, that is covered elsewhere in the guide)
- sectorRisks: 2-3 concrete, sector-specific risks a real ${sector.label} SME using an AI CRM tool could plausibly face, consistent with the six fixed interventions described above

Respond only with the structured JSON output. Do not add commentary outside the schema.`;
}

/**
 * Assembles a complete guide from the sector and whatever sector-specific
 * content is supplied (either the model's parsed response, or the
 * hand-written fallback content for the sector). Every field that isn't
 * sector-specific prose comes straight from data/reference.js, so the
 * live and fallback paths can never disagree on fixed content.
 */
function assembleGuide(sector, sectorContent) {
  return {
    sector: sector.label,
    stakesTier: sector.stakesTier,
    stakesHeading: sectorContent.stakesHeading,
    stakesExplanation: sectorContent.stakesExplanation,
    sectorRisks: sectorContent.sectorRisks,
    article22Caveat: ARTICLE_22_CAVEAT,
    interventions: buildInterventions(sector.stakesTier),
    customerNotice: CUSTOMER_NOTICE,
    disclaimer: DISCLAIMER,
  };
}

module.exports = async (req, res) => {
  if (req.method !== "POST") {
    res.status(405).json({ error: "Method not allowed. Use POST." });
    return;
  }

  let body = req.body;
  if (typeof body === "string") {
    try {
      body = JSON.parse(body);
    } catch {
      body = {};
    }
  }
  body = body || {};

  const sector = getSector(body.sectorId);

  if (!sector) {
    res.status(400).json({
      error: "Invalid sectorId.",
      validSectors: SECTORS.map((s) => s.id),
    });
    return;
  }

  // Reliability boundary: everything from here to the response is wrapped
  // so that ANY failure (missing key, network error, timeout, an
  // unexpected response shape) falls through to the verified fallback
  // rather than surfacing an error to the end user.
  try {
    if (!process.env.ANTHROPIC_API_KEY) {
      throw new Error("ANTHROPIC_API_KEY is not configured.");
    }

    const client = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY });

    const response = await client.messages.create({
      model: MODEL,
      max_tokens: 2048,
      system: buildSystemPrompt(sector),
      output_config: {
        format: { type: "json_schema", schema: OUTPUT_SCHEMA },
      },
      messages: [
        {
          role: "user",
          content: `Write the sector-specific stakes heading, stakes explanation, and sector risks for ${sector.label}.`,
        },
      ],
    });

    const textBlock = response.content.find((b) => b.type === "text");
    if (!textBlock) {
      throw new Error("No text content in Anthropic response.");
    }

    const sectorContent = JSON.parse(textBlock.text);
    const guide = assembleGuide(sector, sectorContent);

    res.status(200).json({ ...guide, isFallback: false });
  } catch (err) {
    // eslint-disable-next-line no-console
    console.error("Live generation failed, serving fallback guide:", err.message);

    const fallbackContent = getFallbackContent(sector.id);
    const guide = assembleGuide(sector, fallbackContent);

    res.status(200).json({
      ...guide,
      isFallback: true,
      fallbackNote:
        "We couldn't reach the live guide generator, so you're seeing a pre-verified cached version. Everything below has been checked against the same sources as the live guide.",
    });
  }
};
